version: "3.9"

services:
  django_web:
    image: djang_host
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - .:/project
    ports:
     - 8000:8000
    depends_on:
      - migration
  migration:
    image: migration
    build:
      context: .
      dockerfile: Dockerfile.migrations
    volumes:
    - .:/project
