# Generated by Django 3.2.3 on 2021-05-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_email', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('visitor_name', 'visitor_email', 'date')},
            },
        ),
    ]
